name: "Lambda Deployment"

on:
  push:

env:
  TF_CLOUD_ORGANIZATION: "kpolonkiewicz"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "EPA-terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - uses: another-action-that-has-a-cleanup-step@v1

    # - name: Run pytest
    #   run: |
    #     pip install -r requirements.txt
    #     pytest

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform init
      run: |
        cd terraform
        terraform init -reconfigure

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve





    # - name: Upload Configuration
    #   uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
    #   id: apply-upload
    #   with:
    #     workspace: ${{ env.TF_WORKSPACE }}
    #     directory: ${{ env.CONFIG_DIRECTORY }}

    # - name: Create Apply Run
    #   uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
    #   id: apply-run
    #   with:
    #     workspace: ${{ env.TF_WORKSPACE }}
    #     configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

    # - name: Apply
    #   uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
    #   id: apply
    #   with:
    #     run: ${{ steps.apply-run.outputs.run_id }}
    #     comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

    # - name: Sync S3
    #   uses: jakejarvis/s3-sync-action@master
    #   env:
    #     SOURCE_DIR: './src'
    #     AWS_REGION: 'eu-north-1'
    #     AWS_S3_BUCKET: 'tf-state-epa'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
