name: "Lambda Deployment"

run-name: ${{ github.ref_name }} by @${{ github.actor  }}

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  tf_fmt:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Python commands
      run: |
        python3.10 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest main_functions_test.py








    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform init
      run: |
        terraform init -reconfigure
        
    - name: Terraform plan
      run: |
        terraform plan -out tfplan.out

    - name: Terraform Apply
      run: |
        terraform apply tfplan.out
