name: "Lambda Deployment"

on:
  push:

# env:
#   TF_CLOUD_ORGANIZATION: "kpolonkiewicz"
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "EPA-terraform-github-actions"
#   CONFIG_DIRECTORY: "./"

jobs:
  tf_fmt:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # - name: Run pytest
    #   run: |
    #     pip install -r requirements.txt
    #     pytest

    - name: Checkout Repo
      uses: actions/checkout@v1

    # - name: Terraform Init
    #   uses: hashicorp/terraform-github-actions/init@v0.4.0
    #   with:
    #     workspace: ${{ env.TF_WORKSPACE }}
    #     directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Terraform init
      run: |
        terraform init -reconfigure
        
    # - name: Terraform plan
    #   run: |
    #     terraform plan -out tfplan.out

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve