name: "Lambda Deployment"

run-name: ${{ github.ref_name }} by @${{ github.actor  }}

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  tf_fmt:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Run Python commands
      run: |
        python3.10 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV

    - name: Run pytest
      run: |
        pip freeze > requirements.txt
        pip install -r requirements.txt
        pytest main_functions_test.py

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform init
      run: |
        terraform init -reconfigure
        
    - name: Terraform plan
      run: |
        terraform plan -out tfplan.out

    - name: Terraform Apply
      run: |
        terraform apply tfplan.out